enum Facility {
  "OutWound" = "OutPatient office / Wound Care Center",
  "Hospital" = "Hospital Ambulatory Area / Clinic",
  "NonClinic" = "Non-clinic / Home Health resource",
}

enum HomeServices {
  "noClinic" = "No, Clinic only",
  "homeHealth" = "Yes, Home Health",
  "teleHealth" = "Yes, Telehealth",
}
export const data = [
  {
    name: "Northwestern Health Porter",
    outPatient: true,
    address: "85 E US Hwy 6 Valparaiso Indiana ",
    phone: "219-983-8780",
    facility: Facility.Hospital,
    persistantAppt: "Yes",
    homeServices: HomeServices.teleHealth,
    apptRequired: "Physician Order",
    additionalService: "Foot Care, Nephrostomy tube site care weekly, SP, G tube care and replacements etc.", 
  },
  {
    name: "Northwestern Medicine - Lake Forest Hospital Wound Center",
    outPatient: true,
    address: "300 Randall Road, Geneva IL",
    phone: "847-535-7600",
    facility: Facility.Hospital,
    persistantAppt: "Yes",
    homeServices: HomeServices.noClinic,
    apptRequired: "Physician Order",
    additionalService: null, 
  },
  {
    name: "Northwestern Medicine - Delnor Hospital Wound Care",
    outPatient: true,
    address: "300 Randall Road, Geneva IL",
    phone: "630-208-4460",
    facility: Facility.Hospital,
    persistantAppt: "Yes",
    homeServices: HomeServices.noClinic,
    apptRequired: "No Physician Order Needed (For Simple Ostomy Care including Skin Issues",
    additionalService: null, 
  },
  {
    name: "Northwest Home Health & Rehab Services (No Hospital Affiliation)",
    outPatient: true,
    address: "9249 S. Route 31, Lake in the Hills IL",
    phone: "847-854-0186",
    facility: Facility.Hospital,
    persistantAppt: "Yes",
    homeServices: HomeServices.noClinic,
    apptRequired: "Physician Order",
    additionalService: null, 
  },
  {
    name: "Northwest Community Hospital ",
    outPatient: true,
    address: "800 W. Central Rd. Arlington Heights IL ",
    phone: "847-618-3231",
    facility: Facility.OutWound,
    persistantAppt: "Yes",
    homeServices: HomeServices.teleHealth,
    apptRequired: "Physician Order",
    additionalService: "Wound care", 
  },
  {
    name: "NorthShore Highland Park Hospital",
    outPatient: true,
    address: "777 Park Ave. W, Highland Park",
    phone: "847-926-5806",
    facility: Facility.Hospital,
    persistantAppt: "Yes",
    homeServices: HomeServices.noClinic,
    apptRequired: "Physician Order and active patient status",
    additionalService: "Accepts supply donations", 
  },
  {
    name: "NorthShore Glenbrook Hospital",
    outPatient: true,
    address: "2100 Pfingsten Rd. Glenview IL",
    phone: "847-657-5963",
    facility: Facility.Hospital,
    persistantAppt: "Yes",
    homeServices: HomeServices.noClinic,
    apptRequired: "Physician Order",
    additionalService: "Accepts supply donations", 
  },
  {
    name: "NorthShore Evanston Hospital",
    outPatient: true,
    address: "2650 Ridge Ave. Evanston IL",
    phone: "847-570-2417",
    facility: Facility.Hospital,
    persistantAppt: "Yes",
    homeServices: HomeServices.noClinic,
    apptRequired: "Physician Order",
    additionalService: null, 
  },
  {
    name: "Loyola University Medical Center",
    outPatient: true,
    address: "2160 S. 1st Ave. Maywood IL",
    phone: "708-216-8554",
    facility: Facility.Hospital,
    persistantAppt: "Yes",
    homeServices: HomeServices.noClinic,
    apptRequired: "No physician order required unless required by your insurance",
    additionalService: null, 
  },
  {
    name: "Edward-Elmhurst Hospital Wound & Ostomy Care",
    outPatient: true,
    address: "1200 S. York St. Suite 1120, Elmhurst IL",
    phone: "331-221-6090",
    facility: Facility.Hospital,
    persistantAppt: "Yes",
    homeServices: HomeServices.noClinic,
    apptRequired: "Physician Order",
    additionalService: null, 
  },
  {
    name: "CWOCN Independent Consulting Services",
    outPatient: true,
    address: "57 E Crestview Dr. Winamac IN",
    phone: "219-252-1155",
    facility: Facility.NonClinic,
    persistantAppt: "Yes",
    homeServices: HomeServices.teleHealth,
    apptRequired: "Patient can refer self and then obtain a physician order if possible",
    additionalService: "Intimacy counseling, diet education all ostomy education and care, Incontinence Kegel education"
  },
  {
    name: "Community Hospital",
    outPatient: true,
    address: "901 MacArthur Blvd, Munster IN",
    phone: "219-836-7713",
    facility: Facility.OutWound,
    persistantAppt: "Yes",
    homeServices: HomeServices.noClinic,
    apptRequired: "Physician Order",
    additionalService: null
  },
  {
    name: "Central Dupage Hospital",
    outPatient: true,
    address: "25 N Winfield Road, Winfield IL",
    phone: "630-933-1480",
    facility: Facility.Hospital,
    persistantAppt: "Yes",
    homeServices: HomeServices.noClinic,
    apptRequired: "Northwestern Medicine Medical Record Number",
    additionalService: null
  },
  {
    name: "Advocate Sherman",
    outPatient: true,
    address: "1425 N. Randall Road, Elgin IL",
    phone: "224-783-3450",
    facility: Facility.Hospital,
    persistantAppt: "Unknown",
    homeServices: HomeServices.noClinic,
    apptRequired: "Physician Order",
    additionalService: null
  },
  {
    name: "Advocate Aurora",
    outPatient: true,
    address: "450 W. Highway22, Barrington IL",
    phone: "847-842-4372",
    facility: Facility.OutWound,
    persistantAppt: "Yes",
    homeServices: HomeServices.noClinic,
    apptRequired: "Physician Order",
    additionalService: null
  },
  {
    name: "Advocate Good Samaritan",
    outPatient: false,
    address: "3815 Highland Ave, Downers Grove IL",
    phone: "630-275-4303",
    facility: Facility.Hospital,
    persistantAppt: "No",
    homeServices: HomeServices.noClinic,
    apptRequired: "A recent ostomy surgery at this location & a physician with privileges at this facility/location",
    additionalService: "Accepts supply donations"
  },
  {
    name: "Advocate Lutheran General",
    outPatient: true,
    address: "1775 Dempster st. Park Ridge IL",
    phone: "847-723-8815",
    facility: Facility.Hospital,
    persistantAppt: "Yes",
    homeServices: HomeServices.noClinic,
    apptRequired: "Physician Order",
    additionalService: "Accepts supply donations"
  },
]
